sudo: false
language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
  - composer install
  - mysql -e 'create database writerzbayauth;'
  - mysql -u root writerzbayauthtest < database_mysql.sql

script:
    - phpunit

notifications:
    email: false
